### ISSUE TITLE
Alpha Mapping on Shadows In Game

### ISSUE THREAD

**Issue by Spuffyre** [Shaderlayan/Atramentum-Luminis-Resources#1]
![image](https://user-images.githubusercontent.com/132760443/236626660-b029b612-28fc-4384-a197-888b30148b56.png)
![image](https://user-images.githubusercontent.com/132760443/236626666-d0e16c23-c2aa-4911-b58e-fb39631964b0.png)

For some reason, on tops like Blade's Harness of Fending where the arms are displayed on a chestpiece. There is no shadow generated on the ground for the arms.

**Comment by Spuffyre** [comment]
![image](https://user-images.githubusercontent.com/132760443/236627058-8f9e1cc3-61e5-45c7-86da-64e4a1697916.png)
Upon second inspection, there's no shadow for the whole body actually.

**Comment by Exter-N** [comment]
The newly-released 3.1.0 update fixes this bug.
